theme: jekyll-theme-minimal
title: BioInfo Site 
logo: https://www.google.com/url?sa=t&source=web&rct=j&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Fhappy-chihuahua&ved=0CBYQjRxqFwoTCOjRmYXI85QDFQAAAAAdAAAAABAG&opi=89978449
