theme: jekyll-theme-minimal
title: BioInfo Site 
logo: https://www.google.com/url?sa=t&source=web&rct=j&url=https%3A%2F%2Fwww.redbubble.com%2Fi%2Fposter%2Fsmiling-chihuahua-by-woollymonkey%2F47975955%2Fflk2&ved=0CBYQjRxqFwoTCMCA9NKU95QDFQAAAAAdAAAAABA8&opi=89978449
